kind: pipeline
type: docker
name: cockroach-arm64

steps:
- name: first build
  image: ubuntu
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
    - apt-get update
    - apt-get -y upgrade 
    - apt-get -y install gcc golang cmake autoconf wget bison libncurses-dev
    - wget -qO- https://binaries.cockroachdb.com/cockroach-v20.2.8.src.tgz | tar  xvz
    - cd cockroach-v20.2.8
    - make build