name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    timeout-minutes: 1440
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Define tag variables
      run: |
          echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Build image
      timeout-minutes: 1440
      run: docker buildx build . --file Dockerfile --tag simcax/cockroach:${{ env.TAG }} --platform=linux/arm64 
    - name: Docker Login
      run: docker login -u="${{ secrets.DOCKERUSERNAME }}" -p="${{ secrets.DOCKERPASSWORD }}"
    - name: Docker Push
      run: docker push simcax/cockroach:${{ env.TAG }}
    
